### ISSUE TITLE
Leaves not generated by the simulation

### ISSUE THREAD

**Issue by Rreboot8x5a** [Plant-Root-Soil-Interactions-Modelling/CPlantBox#3]
Good morning everyone, 

I am currently using CPlantBox to develop the architecture of the Arabidopsis Thaliana. 

To do so, I need to be able to set leaves as successor of all the stems. Though it is possible with the main stem (by setting a leaf organ and a stem organ with the same subType and then only change the _la_ default value of the stem by 0), it is not possible with secondary stems (i.e. stems successor of the main stem). 

More precisely, the code run without problem, but no leaves are created on the secondary stems. 

There is the important part of the code used :
[buggy_leaves.zip](https://github.com/Plant-Root-Soil-Interactions-Modelling/CPlantBox/files/5094341/buggy_leaves.zip)

And there is a commented picture of the result :
![leaves_not_appaering](https://user-images.githubusercontent.com/44650226/90598477-67067380-e1f3-11ea-93a9-de95a471cfaf.png)

I hope this problem is explained well enough.

Thank you in advance for the help.

**Comment by xiaoranzhou** [comment]
Hi Rreboot8x5a,

Thanks for your information. Your question is made very clear and it is an interesting and helpful issue.

As you have discovered, the invisible stem is important, because it is used as a bud to grow leaves.
However, a bud stem should be only subtype 2 stem, and it grow only the subtype 2 leaf.

I have modified your code to create the following code, which generate the following screen shot.
One bug still exist: sometimes the stem turned into leaves and sometimes there is less stem.
I don't know if it is a python parameter (nomally xml parameters are used) issue or a child node calculation issue.
Hopefully, you can just run the code multiple times to find the best outcome.

Sorry for the inconvenience, as the plant structure is truly flexible and diverse, an omini and bug-free system is hard to achieve. Just like the bud mutation still exist in plants.  



`# Generating the plant architecture 
from CPlantBox_PiafMunch import * #import all the libraries
rs = pb.Plant()
p0 = pb.RootRandomParameter(rs)  # with default values,
p1 = pb.RootRandomParameter(rs)  # all standard deviations are 0
s1 = pb.StemRandomParameter(rs)
s2 = pb.StemRandomParameter(rs)
s3 = pb.StemRandomParameter(rs)
s4 = pb.StemRandomParameter(rs)
l1 = pb.LeafRandomParameter(rs)
l2 = pb.LeafRandomParameter(rs)

p0.name = "taproot"
p0.a = 0.2  # [cm] radius
p0.subType = 1  # [-] index starts at 1
p0.lb = 5  # [cm] basal zone
p0.la = 10  # [cm] apical zone
p0.lmax = 30  # [cm] maximal root length, number of lateral branching nodes = round((lmax-lb-la)/ln) + 1
p0.ln = 1.  # [cm] inter-lateral distance (16 branching nodes)
p0.theta = 0.  # [rad]
p0.r = 1  # [cm/day] initial growth rate
p0.dx = 10  # [cm] axial resolution
p0.successor = [2]  # add successors
p0.successorP = [1]  # probability that successor emerges
p0.tropismT = pb.TropismType.gravi  #
p0.tropismN = 1.8  # [-] strength of tropism
p0.tropismS = 0.2  # [rad/cm] maximal bending

p1.name = "lateral"
p1.a = 0.1  # [cm] radius
p1.subType = 2  # [1] index starts at 1
p1.lmax = 15  # # [cm] apical zone
p1.lmaxs = 0.15  # [cm] standard deviation of the apical zone
p1.theta = 90. / 180. * np.pi  # [rad]
p1.r = 2  # initial growth rate
p1.dx = 1  # [cm] axial resolution
p1.tropismT = pb.TropismType.gravi  # exo
p1.tropismN = 2  # [-] strength of tropism
p1.tropismS = 0.1  # [rad/cm] maximal bending

s1.name = "mainstem"
s1.subType = 1

s1.lmax = 50
s1.lb = 2
s1.la = 1
s1.ln = 4
s1.lnf = 0
s1.RotBeta = 0
s1.BetaDev = 0
s1.InitBeta = 0
s1.gf = 1
s1.successor = [3,2]
s1.successorP = [0.5,0.5]
s1.tropismT = 4
s1.theta = 0.
s1.tropismN = 18
s1.tropismS = 0.01
s1.r = 1



s3.name = "invisible stem"
s3.subType = 2
s3.lmax = 5
s3.la = 0
s3.ln = 0
s3.RotBeta = 0
s3.BetaDev = 0
s3.InitBeta = 0.
s3.lb = 0
s3.la = 0
s3.ln = 0
s3.lnf = 0
s3.RotBeta = 2 / 3
s3.BetaDev = 0
s3.InitBeta = 0
s3.gf = 1
s3.tropismT = 1
s3.theta = 0.3
s3.tropismN = 18
s3.tropismS = 0.01
s3.r = 1


s2.name = "secondary_stem"
s2.subType = 3
s2.lmax = 10
s2.lb = 0
s2.la = 2
s2.ln = 2
s2.lnf = 0
s2.RotBeta = 2 / 3
s2.BetaDev = 0
s2.InitBeta = 0
s2.gf = 1
s2.successor = [2]
s2.successorP = [1]
s2.tropismT = 4
s2.theta = 0.3
s2.tropismN = 18
s2.tropismS = 0.01
s2.r = 0.5

l1.name = 'leaf_under_second_stem'
l1.subType = 2
l1.lb = 2
l1.la = 0.2
l1.lmax = 5
l1.r = 0.5
l1.RotBeta = 0.5
l1.BetaDev = 0
l1.InitBeta = 0.
l1.tropismT = 1
l1.tropismN = 5
l1.tropismS = 0.15
l1.theta = 0.35
l1.gf = 1

l2.name = 'leaf_on_second_stem'
l2.subType = 3
l2.lb = 2
l2.la = 0.2
l2.lmax = 5
l2.r = 0.5
l2.RotBeta = 0.5
l2.BetaDev = 0
l2.InitBeta = 0.
l2.tropismT = 1
l2.tropismN = 5
l2.tropismS = 0.15
l2.theta = 0.35
l2.gf = 1

s4.name = "rosette"
s4.subType = 4
s4.lmax = 2
s4.lb = 1
s4.la = 0
s4.ln = 2
s4.lnf = 0
s4.RotBeta = 1 / 5
s4.BetaDev = 0
s4.InitBeta = 0
s4.gf = 1
s4.tropismT = 1
s4.theta = 0.3
s4.tropismN = 18
s4.tropismS = 0.01
s4.r = 0.5

rs.setOrganRandomParameter(p0)
rs.setOrganRandomParameter(p1)
rs.setOrganRandomParameter(s1)
rs.setOrganRandomParameter(s2)
rs.setOrganRandomParameter(s3)
rs.setOrganRandomParameter(s4)
rs.setOrganRandomParameter(l1)

srp = pb.SeedRandomParameter(rs)  # with default values
srp.seedPos = pb.Vector3d(0., 0., -3.)  # [cm] seed position
srp.maxB = 0  # [-] number of basal roots (neglecting basal roots and shoot borne)
srp.firstB = 10.  # [day] first emergence of a basal root
srp.delayB = 3.  # [day] delay between the emergence of basal roots
srp.maxTil = 10
rs.setOrganRandomParameter(srp)

#  Simulating the plant growth

time = 70

rs.initialize(True)

rs.simulate(time)

fig = visual_plant(rs)

fig.show()`
 correct figures
![newplot](https://user-images.githubusercontent.com/29843510/90603929-5a3a4d80-e1fc-11ea-9369-e21cbc9d6032.png)
![newplot (1)](https://user-images.githubusercontent.com/29843510/90605355-8060ed00-e1fe-11ea-9202-e105ea0ef1e6.png)
buggy figures
![newplot (2)](https://user-images.githubusercontent.com/29843510/90605469-aedec800-e1fe-11ea-8ee5-3777672ecebd.png)

**Comment by xiaoranzhou** [comment]
@Rreboot8x5a issue is closed, due to no further feedback and presumably solved :D
