### ISSUE TITLE
ask a question

### ISSUE THREAD

**Issue by Chiaki59** [Plant-Root-Soil-Interactions-Modelling/CPlantBox#52]
In the cords of CPlantBox_PiafMunch.py
where or what is the module plantbox.py ? I couldn't detect.

**Comment by xiaoranzhou** [comment]
Hi Chiaki59,

thanks for your message and question.

the plantbox module is not a plain python script (so to say, does not have a ".py" suffix). 
Actually, it is a compiled binary excutable of CPlantBox, which I added in the root folder of [CPlantBox](https://github.com/Plant-Root-Soil-Interactions-Modelling/CPlantBox/commits/d1e2bd06e6e0d5e43c90c10fa8f8c1d31fc19912/plantbox.cpython-36m-x86_64-linux-gnu.so) 

Due to some reason, we decide to remove this excutable to prevent confusion. That is why the CPlantBox_PiafMunch.py can not run without compiling.

to compensate for the inconvenience, I prepared a simplified fork with compiled binary

There is also a binder link prepared for testing 
https://mybinder.org/v2/gh/xiaoranzhou/cpb-binder/main?labpath=tutorial%2Fjupyter%2FCPlantBox_tutorial_FSPM2020.ipynb

the fig.show() function currently has some problem, you can use the following code to display some figures 
plotly.offline.plot(fig, filename='champagnat.html')
from IPython.display import HTML
HTML("champagnat.html")
